### ISSUE TITLE
[Bug]: Theme name with more than one word

### ISSUE THREAD

**Issue by zcysxy** [Lisandra-dev/obsidian-group-snippets#2]
Thanks for this plugin! I don't know if it is a bug: When the theme name in the group name is more than one word, for example, `Shimmering Focus`, the auto-toggle based on theme switch doesn't work anymore.

**Comment by Mara-Li** [comment]
I will check that ! Never tried with "long theme"

**Comment by Mara-Li** [comment]
Seems it was fixed by my very last update, the 1.6.1. Creating a group named "Shimmering Focus" link the good theme. Same for "Shimmering Focus Light"

![image](https://user-images.githubusercontent.com/30244939/184625009-296ffd71-a9d6-4b04-9267-c39bb9c1e4fc.png)

**Comment by zcysxy** [comment]
Hi! I guess this brings up some issues again. Every time I switch to a "long theme", such as Shimmering Focus and Blue Topaz, the group default is also activated
<img width="355" alt="image" src="https://user-images.githubusercontent.com/48207708/202640355-e9f169bd-3403-40d5-aac1-51d2faad1084.png">

**Comment by Mara-Li** [comment]
Is the group default must be linked to the default theme (aka Obsidian theme) or it's a default group ? 
I don't think I linked `default` with Obsidian default theme.

**Comment by zcysxy** [comment]
> Is the group default must be linked to the default theme (aka Obsidian theme) or it's a default group ?
> I don't think I linked `default` with Obsidian default theme.

Ah that makes sense. Then how can I link one group to the default theme?
