### ISSUE TITLE
[Bug] Unable to use the plugin: nothing happens after naming a group

### ISSUE THREAD

**Issue by Evelf** [Lisandra-dev/obsidian-group-snippets#3]
I've just downloaded the plugin and I can't make it works.

I try to create a new group, give it a name ("plop") and save, but the group is not created. There's an error in the console log (see attachment).

I asked on obsidian's discord, someone else tried without success. We are on the 1.0 release if that matters.
[obsidian.md-1665834766712.log](https://github.com/Lisandra-dev/obsidian-group-snippets/files/9791956/obsidian.md-1665834766712.log)

**Comment by Mara-Li** [comment]
Sorry, I forgot to bump the version out of the bêta ! 
Thanks you for this information :)
I released the 1.8.3, which resolve the last bug.
