### ISSUE TITLE
[FR]: add a icon in statusbar for popup the snippts group menu 

### ISSUE THREAD

**Issue by cloudherder** [Lisandra-dev/obsidian-group-snippets#4]
### Issue validation

- [X] I checked the issue to prevent duplicate

### What solution do you want to see ?

Please add a icon in statusbar for popup the snippts group menu like mysnippts-plugin , it make easy to enable/disable a group snippts. 

### OS

Windows

**Comment by Mara-Li** [comment]
Hello! Sorry for the delay, I have no notif of open FR/issue.

I don't think I will do that. As an alternative, you could use commander. As the plugin add commands, you can add it in the status bar (or anywhere you want).

Link to commander : https://github.com/phibr0/obsidian-commander
